(function(f){function p(){p.done||(B=p.done=!0,C=!1,b.each(q,function(a){a._dom_loaded()}))}var w=[],D=Array.prototype,r=Object.prototype,E=D.slice,x=r.toString,y=r.hasOwnProperty,m=window.console,z=window.navigator,k=window.document,t=z.userAgent,F="http:"==k.location.protocol?"http://":"https://",r=f&&f.__SV||0,A=window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest,C=!A&&-1==t.indexOf("MSIE")&&-1==t.indexOf("Mozilla"),b={},H={api_host:F+"api.cooladata.com",loaded:function(){},img:!1,http_post:!1,
track_pageload:!1,cookie_expiration:365,disable_cookie:!1,cookie_name:"cd_user_id"},B=!1;(function(){var a=D.forEach,g=Array.isArray,e={},d=b.each=function(d,g,b){if(null!=d)if(a&&d.forEach===a)d.forEach(g,b);else if(d.length===+d.length)for(var c=0,f=d.length;c<f&&!(c in d&&g.call(b,d[c],c,d)===e);c++);else for(c in d)if(y.call(d,c)&&g.call(b,d[c],c,d)===e)break};b.extend=function(a){d(E.call(arguments,1),function(e){for(var d in e)void 0!==e[d]&&(a[d]=e[d])});return a};b.isArray=g||function(a){return"[object Array]"===
x.call(a)};b.isFunction=function(a){try{return/^\s*\bfunction\b/.test(a)}catch(e){return!1}};b.isArguments=function(a){return!(!a||!y.call(a,"callee"))};b.toArray=function(a){return a?a.toArray?a.toArray():b.isArray(a)||b.isArguments(a)?E.call(a):b.values(a):[]};b.values=function(a){var e=[];if(null==a)return e;d(a,function(a){e[e.length]=a});return e}})();b.isObject=function(a){return a===Object(a)&&!b.isArray(a)};b.isUndefined=function(a){return void 0===a};b.isString=function(a){return"[object String]"==
x.call(a)};b.JSONEncode=function(){return function(a){var g=function(a){var e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var e=g[a];return"string"===typeof e?e:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'},e=function(a,b){var h="",c=0,s=c="",s=0,f=h,n=[],l=
b[a];l&&"object"===typeof l&&"function"===typeof l.toJSON&&(l=l.toJSON(a));switch(typeof l){case "string":return g(l);case "number":return isFinite(l)?String(l):"null";case "boolean":case "null":return String(l);case "object":if(!l)return"null";h+="    ";n=[];if("[object Array]"===x.apply(l)){s=l.length;for(c=0;c<s;c+=1)n[c]=e(c,l)||"null";return s=0===n.length?"[]":h?"[\n"+h+n.join(",\n"+h)+"\n"+f+"]":"["+n.join(",")+"]"}for(c in l)y.call(l,c)&&(s=e(c,l))&&n.push(g(c)+(h?": ":":")+s);return s=0===
n.length?"{}":h?"{"+n.join(",")+""+f+"}":"{"+n.join(",")+"}"}};return e("",{"":a})}}();b.strip_empty_properties=function(a){var g={};b.each(a,function(a,d){b.isString(a)&&0<a.length&&(g[d]=a)});return g};b.base64Encode=function(a){var g={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d",encode:function(a){var d="",b,h,c,f,k,n,l=0;for(a=g._utf8_encode(a);l<a.length;)b=a.charCodeAt(l++),h=a.charCodeAt(l++),c=a.charCodeAt(l++),f=b>>2,b=(b&3)<<4|h>>4,k=(h&15)<<2|c>>6,n=c&
63,isNaN(h)?k=n=64:isNaN(c)&&(n=64),d=d+this._keyStr.charAt(f)+this._keyStr.charAt(b)+this._keyStr.charAt(k)+this._keyStr.charAt(n);return d},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var d="",g=0;g<a.length;g++){var b=a.charCodeAt(g);128>b?d+=String.fromCharCode(b):(127<b&&2048>b?d+=String.fromCharCode(b>>6|192):(d+=String.fromCharCode(b>>12|224),d+=String.fromCharCode(b>>6&63|128)),d+=String.fromCharCode(b&63|128))}return d}};return g.encode(a)};b.utf8Encode=function(a){a=a.replace(/\r\n/g,
"\n");for(var b="",e=0;e<a.length;e++){var d=a.charCodeAt(e);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b};b.HTTPBuildQuery=function(a,g){var e,d,c=[];"undefined"===typeof g&&(g="\x26");b.each(a,function(a,b){e=encodeURIComponent(a.toString());d=encodeURIComponent(b);c[c.length]=d+"\x3d"+e});return c.join(g)};b.UUID=function(){var a=function(){for(var a=
1*new Date,b=0;a==1*new Date;)b++;return a.toString(16)+b.toString(16)},b=function(a){function b(a,e){var d,g=0;for(d=0;d<e.length;d++)g|=c[d]<<8*d;return a^g}var g,c=[],f=0;for(a=0;a<t.length;a++)g=t.charCodeAt(a),c.unshift(g&255),4<=c.length&&(f=b(f,c),c=[]);0<c.length&&(f=b(f,c));return f.toString(16)};return function(){var e=(screen.height*screen.width).toString(16);return a()+"-"+Math.random().toString(16).replace(".","")+"-"+b()+"-"+e+"-"+a()}}();b.getQueryParam=function(a,b){b=b.replace(/[\[]/,
"\\[").replace(/[\]]/,"\\]");var e=(new RegExp("[\\?\x26]"+b+"\x3d([^\x26#]*)")).exec(a);return null===e||e&&"string"!==typeof e[1]&&e[1].length?"":decodeURIComponent(e[1]).replace(/\+/g," ")};b.register_event=function(){function a(a,d,c){return function(h){if(h=h||g(window.event)){var f=!0,k;b.isFunction(c)&&(k=c(h));h=d.call(a,h);if(!1===k||!1===h)f=!1;return f}}}function g(a){a&&(a.preventDefault=g.preventDefault,a.stopPropagation=g.stopPropagation);return a}g.preventDefault=function(){this.returnValue=
!1};g.stopPropagation=function(){this.cancelBubble=!0};return function(b,d,g,c){b?b.addEventListener&&!c?b.addEventListener(d,g,!1):(d="on"+d,b[d]=a(b,g,b[d])):m.log("No valid element provided to register_event")}}();b.info={campaignParams:function(){var a="",g={};b.each(["utm_source","utm_medium","utm_campaign","utm_content","utm_term"],function(e){a=b.getQueryParam(k.URL,e);a.length&&(g[e]=a)});return g},referringDomain:function(a){a=a.split("/");return 3<=a.length?a[2]:""},properties:function(){return b.extend(b.strip_empty_properties({session_screen_size:window.screen.width+
"x"+window.screen.height,session_dua:z.userAgent,session_platform:z.platform,referring_url:k.referrer,referring_domain:b.info.referringDomain(k.referrer)}),{tracker_type:"javascript",tracker_version:"2.1.15"})},pageviewInfo:function(a){return b.strip_empty_properties({event_timestamp_epoch:1*new Date,page_url:window.location.protocol+"//"+window.location.host+window.location.pathname,page_title:k.title})}};var I={critical:function(){if(!b.isUndefined(m)&&m){var a=["Cooladata error:"].concat(b.toArray(arguments));
try{m.error.apply(m,a)}catch(g){b.each(a,function(a){m.error(a)})}}}},v=function(a,g,e){var d,u="cooladata"===e?f:f[e];if(u&&!b.isArray(u))m.log("You have already initialized "+e);else return d=new c,d._init(a,g,e),b.isUndefined(u)||d._execute_array(u),d},c=function(){};c.prototype.init=function(a,b,e){if("undefined"===typeof e)m.log("You must name your new library: init(token, config, name)");else if("cooladata"===e)m.log("You must initialize the main cooladata object right after you include the Cooladata js snippet");
else return a=v(a,b,e),f[e]=a,a._loaded(),a};c.prototype._init=function(a){this.__loaded=!0;this.config={};this.set_config(b.extend({},H,{token:a.app_key,img:a.img_src_get_request,session_id:a.session_id,http_post:a.http_post,track_pageload:a.track_pageload,disable_cookie:a.disable_cookie}));a.api_host&&this.set_config({api_host:F+a.api_host});a.cookie_expiration&&this.set_config({cookie_expiration:a.cookie_expiration});if(a.user_id)this.set_config({user_id:a.user_id});else if(this.get_config("disable_cookie"))this.set_config({user_id:b.UUID()});
else{var g=this.get_config("cookie_name"),e=this.getCookie(g);""==e?(this.setCookie(g),e=this.getCookie(g),""==e?this.set_config({user_id:b.UUID()}):this.set_config({user_id:e})):this.set_config({user_id:e})}this.__dom_loaded_queue=[];this.__request_queue=[];a.custom_event_handler&&(this.__customEventHandler=a.custom_event_handler)};c.prototype.getCookie=function(a){a+="\x3d";for(var b=k.cookie.split(";"),e=0;e<b.length;e++){for(var d=b[e];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,
d.length)}return""};c.prototype.setCookie=function(a){var g=this.get_config("cookie_expiration"),e=new Date;e.setTime(e.getTime()+864E5*g);var g="; expires\x3d"+e.toGMTString(),e="com org net int edu gov mil biz".split(" "),d=window.location.host.split("."),c="";if("www"==d[0]||4==d.length)d.shift(),c=d.join(".");else switch(d.length){case 2:c=d.join(".");break;case 3:for(var h=e.length;h--;)if(e[h]===d[2]){d.shift();c=d.join(".");break}""==c&&(c=d.join("."))}k.cookie=a+"\x3d"+b.UUID()+g+";domain\x3d."+
c+";path\x3d/"};c.prototype._loaded=function(){this.get_config("loaded")(this);this.get_config("track_pageload")&&this.track_pageload()};c.prototype._dom_loaded=function(){b.each(this.__dom_loaded_queue,function(a){this._track_dom.apply(this,a)},this);b.each(this.__request_queue,function(a){this._send_request.apply(this,a)},this);delete this.__dom_loaded_queue;delete this.__request_queue};c.prototype._track_dom=function(a,b){if(this.get_config("img"))return m.log("You can't use DOM tracking functions with img \x3d true."),
!1;if(!B)return this.__dom_loaded_queue.push([a,b]),!1;var e=(new a).init(this);return e.track.apply(e,b)};c.prototype.trackEventLater=function(a,c){if("undefined"===typeof a)m.log("No event name provided to cooladata.trackEventLater");else{c=c||{};var e=new Date,e=b.extend({},b.info.properties(),b.info.campaignParams(),{event_name:a,event_timestamp_epoch:e.getTime().toString(),event_timezone_offset:-1*(e.getTimezoneOffset()/60),user_id:this.get_config("user_id"),session_id:this.get_config("session_id")}),
e=b.extend(e,c);w.push(e)}};c.prototype.flush=function(){this.get_config("api_host");this.get_config("token");var a=b.JSONEncode({events:w});this._send_request(a);w=[]};c.prototype._onError=function(a,b){};c.prototype._send_request=function(a,c){if(C)this.__request_queue.push(arguments);else{var e=function(){var a=window.navigator.userAgent;return-1<a.indexOf("MSIE ")&&1!==a.split("MSIE ")[1].charAt(0)?!0:!1},d=!1;1400<a.length&&(d=!0);if(this.__customEventHandler&&this.__customEventHandler.handleRequest){var f=
null;d||!e()&&!this.get_config("img")?A&&(f=this.get_config("http_post")||d?"post":"get"):f="image";this.__customEventHandler.handleRequest(this,a,f)}else if(f=this.get_config("api_host")+"/v1/"+this.get_config("token")+"/track",d||!e()&&!this.get_config("img"))if(A){e=null;this.get_config("http_post")||d?e="data\x3d"+encodeURIComponent(a):(a={data:b.base64Encode(a)},f+="?"+b.HTTPBuildQuery(a));var h=new XMLHttpRequest;this.get_config("http_post")||d?(h.open("POST",f,!0),h.setRequestHeader("Content-type",
"application/x-www-form-urlencoded")):h.open("GET",f,!0);h.withCredentials=!0;h.onreadystatechange=function(a){4===h.readyState&&(200===h.status?c&&c():m.log("Bad HTTP status: "+h.status+" "+h.statusText))};h.send(e)}else d=k.createElement("script"),d.type="text/javascript",d.async=!0,d.defer=!0,d.src=f,f=k.getElementsByTagName("script")[0],f.parentNode.insertBefore(d,f);else{var p=this,f=this.get_config("api_host")+"/egw/5/"+this.get_config("token")+"/track/__cool.gif";a=b.base64Encode(a);f+="?data\x3d"+
a;d=k.createElement("img");d.onerror=function(){p._onError(a,c)};d.width=1;d.height=1;d.src=f}}};c.prototype._execute_array=function(a){var c,e=[],d=[],f=[];b.each(a,function(a){a&&(c=a[0],"function"===typeof a?a.call(this):b.isArray(a)&&"alias"===c?e.push(a):b.isArray(a)&&-1!=c.indexOf("track")&&"function"===typeof this[c]?f.push(a):d.push(a))},this);a=function(a,d){b.each(a,function(a){this[a[0]].apply(this,a.slice(1))},d)};a(e,this);a(d,this);a(f,this)};c.prototype.push=function(a){this._execute_array([a])};
c.prototype.trackEvent=function(a,c,e){if("undefined"===typeof a)m.log("No event name provided to cooladata.trackEvent");else{c=c||{};var d=new Date;a=b.extend({},b.info.properties(),b.info.campaignParams(),{event_name:a,event_timestamp_epoch:d.getTime().toString(),event_timezone_offset:-1*(d.getTimezoneOffset()/60),user_id:this.get_config("user_id"),session_id:this.get_config("session_id")});a=b.extend(a,c);a={events:[a]};c=b.JSONEncode(a);this._send_request(c,e)}};c.prototype.track_pageload=function(a){"undefined"===
typeof a&&(a=k.location.href);this.trackEvent("page_load",b.info.pageviewInfo(a))};c.prototype.set_config=function(a){b.isObject(a)&&b.extend(this.config,a)};c.prototype.get_config=function(a){return this.config[a]};c.prototype.toString=function(){var a=this.get_config("name");"cooladata"!==a&&(a="cooladata."+a);return a};b.toArray=b.toArray;b.isObject=b.isObject;b.JSONEncode=b.JSONEncode;b.info=b.info;c.prototype.init=c.prototype.init;c.prototype.track_event=c.prototype.trackEvent;c.prototype.track_event_later=
c.prototype.trackEventLater;c.prototype.flush=c.prototype.flush;c.prototype.track_pageload=c.prototype.track_pageload;c.prototype.set_config=c.prototype.set_config;c.prototype.get_config=c.prototype.get_config;c.prototype.toString=c.prototype.toString;if(b.isUndefined(f))I.critical("'cooladata' object not initialized. Ensure you are using the latest version of the Cooladata JS Library along with the snippet we provide.");else if(f.__loaded||f.config)m.log("Cooladata library has already been downloaded at least once.");
else if(1.1>r)m.critical("Version mismatch; please ensure you're using the latest version of the Cooladata code snippet.");else{var q={};b.each(f._i,function(a){var c;a&&b.isArray(a)&&(c=a[a.length-1],a=v.apply(this,a),q[c]=a)});var J=function(){b.each(q,function(a,b){"cooladata"!==b&&(f[b]=a)});f._=b};f.init=function(a,b,c){c?f[c]||(f[c]=q[c]=v(a,b,c),f[c]._loaded()):(c=f,q.cooladata?c=q.cooladata:a&&(c=v(a,b,"cooladata"),c._loaded()),window.cooladata=f=c,J())};f.init();b.each(q,function(a){a._loaded()});
if(k.addEventListener)"complete"==k.readyState?p():k.addEventListener("DOMContentLoaded",p,!1);else if(k.attachEvent){k.attachEvent("onreadystatechange",p);r=!1;try{r=null==window.frameElement}catch(K){}if(k.documentElement.doScroll&&r){var G=function(){try{k.documentElement.doScroll("left")}catch(a){setTimeout(G,1);return}p()};G()}}b.register_event(window,"load",p,!0)}})(window.cooladata);
